AWSTemplateFormatVersion: '2010-09-09'
Resources:
  MyECSCluster:
    Type: 'AWS::ECS::Cluster'

  MyTaskDefinition:
    Type: 'AWS::ECS::TaskDefinition'
    Properties:
      Family: my-fargate-task
      Cpu: '256'
      Memory: '512'
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: 'arn:aws:iam::YourAccountID:role/ecsTaskExecutionRole'
      ContainerDefinitions:
        - Name: my-fargate-container
          Image: your-docker-image
          PortMappings:
            - ContainerPort: 80

  MyFargateService:
    Type: 'AWS::ECS::Service'
    Properties:
      Cluster: !Ref MyECSCluster
      LaunchType: FARGATE
      DesiredCount: 1
      TaskDefinition: !Ref MyTaskDefinition
      NetworkConfiguration:
        AwsvpcConfiguration:
          Subnets:
            - subnet-12345678
            - subnet-87654321
          SecurityGroups:
            - sg-0123456789abcdef0
