  AWSTemplateFormatVersion: '2010-09-09'
  MyEC2Instance: 
    Type: AWS::EC2::Instance
    Properties: 
      AvailabilityZone: us-west-2
      ImageId: "ami-79fd7eee"
      InstanceType: t2.micro
      Keyname: "oregon-docs"
      BlockDeviceMappings:
      - DeviceName: /dev/sda1
        Ebs:
          VolumeType: "gp3"
          VolumeSize: 50
          DeleteOnTermination: "true"
      - DeviceName: /dev/sdm
        Ebs:
          VolumeSize: 100
      SecurityGroups:
        - Ref: InstanceSecurityGroup    

  InstanceSecurityGroup:
  Type: AWS::EC2::SecurityGroup
  Properties:
    GroupDescription: Allow http to client host
    
    SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0
    SecurityGroupEgress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
