Description: The template used to create an ECS Task definition from the ECS Console.
Resources:
  ECSTaskDefinition:
    Type: 'AWS::ECS::TaskDefinition'
    Properties:
      ContainerDefinitions:
        - Name: test-container-task
          Image: >-
            3375835250337583525037.dkr.ecr.us-west-2.amazonaws.com/testing-admin-image
          MemoryReservation: 1024
          PortMappings:
            - ContainerPort: 80
              HostPort: 80
              Protocol: tcp
            - ContainerPort: 22
              HostPort: 22
              Protocol: tcp
          Environment: []
          MountPoints: []
          VolumesFrom: []
          ReadonlyRootFilesystem: true
          DnsServers:
            - 8.8.8.8
            - 8.4.4.8
          Essential: true
          Cpu: 0
      Family: betas-test-task
      NetworkMode: bridge
      TaskRoleArn: 'arn:aws:iam::337583525037:role/ecsAdmin'
      ExecutionRoleArn: 'arn:aws:iam::337583525037:role/ecsAdmin'
      PlacementConstraints: []
      RequiresCompatibilities:
        - EC2
      Cpu: 1 vCPU
      Memory: 2 GB
      Tags:
        - Key: 'ecs:taskDefinition:createdFrom'
          Value: ecs-console-v2
        - Key: 'ecs:taskDefinition:stackId'
          Value: !Ref 'AWS::StackId'
Outputs:
  TaskDefinitionARN:
    Description: The created task definition ARN.
    Value: !Ref ECSTaskDefinition