AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create a Security Group for an EC2 instance with SSH access.

Resources:
  BackendEcommerceSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupName: 'backend-ecommerce'
      GroupDescription: 'Security group for backend ecommerce instance allowing SSH access'
      VpcId: 'vpc-2cac1c4b'
      SecurityGroupIngress:
        - IpProtocol: 'tcp'
          FromPort: 22
          ToPort: 22
          CidrIp: '0.0.0.0/0'
        - IpProtocol: tcp
          FromPort: '80'
          ToPort: '80'
          CidrIp: '0.0.0.0/0'
        - IpProtocol: tcp
          FromPort: '443'
          ToPort: '443'
          CidrIp: '0.0.0.0/0'

      Tags:
        - Key: Name
          Value: backend-ecommerce
